### ISSUE TITLE
Add <meta name="darkreader-lock">

### ISSUE THREAD

**Issue by bershanskiy** [nexangelus/dbd_PerkFinder#7]
This is an alternative to https://github.com/darkreader/darkreader/pull/10957

Just add `<meta name="darkreader-lock">` to `<head>` in all documents which should be excluded from Dark Reader.

As far as I see, there is only one such file https://github.com/nexangelus/dbd_PerkFinder/blob/main/docs/index.html

**Comment by andre-paulo98** [comment]
yep! i'll do this instead. Didn't know about that tag!

**Comment by bershanskiy** [comment]
Thanks for quick response!

I verified that the fix works (that https://nexangelus.github.io/dbd_PerkFinder/ is excluded from Dark Reader).

**Comment by andre-paulo98** [comment]
Thank you!
Is that meta tag documented somewhere? Or what other things you could do it with?
